use crate::schema::*;

#[derive(Debug, Queryable,Serialize, Deserialize, Insertable)]
#[table_name="ommu_users"]
pub struct User {
    pub user_id: i32,
    pub enabled: i32,
    pub verified: i32,
    pub level_id: Option<i32>,
    pub language_id: Option<i32>,
    pub email: String,
    pub username: String,
    pub first_name: String,
    pub last_name: String,
    pub displayname: String,
    pub password: String,
    pub photos: Option<String>,
    pub salt: String,
    pub deactivate: i32,
    pub search: i32,
    pub invisible: i32,
    pub privacy: i32,
    pub comments: i32,
    pub creation_date: chrono::NaiveDateTime,
    pub creation_ip: String,
    pub modified_date: chrono::NaiveDateTime,
    pub modified_id: Option<i32>,
    pub lastlogin_date: chrono::NaiveDateTime,
    pub lastlogin_ip: String,
    pub lastlogin_from: String,
    pub update_date: chrono::NaiveDateTime,
    pub update_ip: String,
    pub auth_key: Option<String>,
    pub jwt_claims: Option<String>,
}
